export const TIER_FEATURES = {
  basic: {
    name: "Apollo Core",
    description: "Structured training without nutrition guidance",
    features: [
      "All Apollo training programs",
      "Workout tracking & logging",
      "Exercise demo videos",
      "On-demand workout library",
      "Apollo Academy content",
      "Basic progress tracking",
      "Community challenges",
    ],
    buttonLabel: "Start Training",
  },
  pro: {
    name: "Apollo Fuel",
    description: "Training + the Apollo Fuel nutrition protocol",
    features: [
      "Everything in Apollo Core",
      "Apollo Fuel nutrition system",
      "Meal plans & recipes",
      "Macro tracking dashboard",
      "Auto macro tracking on meals",
      "Grocery lists",
      "Nutrition streak & weekly score",
      "Progress photo tracking",
      "Transformation timeline",
    ],
    buttonLabel: "Start Fuel System",
    featured: true,
  },
  elite: {
    name: "Apollo Elite",
    description: "Full system with personalized coaching",
    features: [
      "Everything in Apollo Fuel",
      "Custom program adjustments",
      "Direct messaging with coaches",
      "Monthly progress reviews",
      "Advanced body composition tracking",
      "Personalized macro adjustments",
      "Priority support",
      "Exclusive member challenges",
      "Early access to new programs",
    ],
    buttonLabel: "Apply for Elite Coaching",
  },
} as const;
