
-- Client nutrition profiles (coach inputs client data)
CREATE TABLE public.client_nutrition_profiles (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL UNIQUE,
  age INTEGER,
  weight_lbs NUMERIC,
  height_inches INTEGER,
  activity_level TEXT DEFAULT 'moderate',
  goals TEXT,
  dietary_preferences TEXT[] DEFAULT '{}',
  food_restrictions TEXT[] DEFAULT '{}',
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Nutrition plans (generated by AI or manually created)
CREATE TABLE public.nutrition_plans (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  created_by UUID NOT NULL,
  title TEXT NOT NULL,
  daily_calories INTEGER,
  protein_grams INTEGER,
  carbs_grams INTEGER,
  fat_grams INTEGER,
  start_date DATE DEFAULT CURRENT_DATE,
  duration_weeks INTEGER DEFAULT 4,
  status TEXT DEFAULT 'active',
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Individual meals within a plan
CREATE TABLE public.nutrition_plan_meals (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  plan_id UUID NOT NULL REFERENCES public.nutrition_plans(id) ON DELETE CASCADE,
  day_number INTEGER NOT NULL,
  meal_type TEXT NOT NULL,
  meal_name TEXT NOT NULL,
  description TEXT,
  ingredients JSONB,
  calories INTEGER,
  protein_grams NUMERIC,
  carbs_grams NUMERIC,
  fat_grams NUMERIC,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS on all tables
ALTER TABLE public.client_nutrition_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nutrition_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nutrition_plan_meals ENABLE ROW LEVEL SECURITY;

-- RLS for client_nutrition_profiles
CREATE POLICY "Admins can manage all nutrition profiles"
ON public.client_nutrition_profiles FOR ALL
USING (has_role(auth.uid(), 'admin'::app_role))
WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Users can view their own nutrition profile"
ON public.client_nutrition_profiles FOR SELECT
USING (auth.uid() = user_id);

-- RLS for nutrition_plans
CREATE POLICY "Admins can manage all nutrition plans"
ON public.nutrition_plans FOR ALL
USING (has_role(auth.uid(), 'admin'::app_role))
WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Users can view their own nutrition plans"
ON public.nutrition_plans FOR SELECT
USING (auth.uid() = user_id);

-- RLS for nutrition_plan_meals
CREATE POLICY "Admins can manage all plan meals"
ON public.nutrition_plan_meals FOR ALL
USING (has_role(auth.uid(), 'admin'::app_role))
WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Users can view their own plan meals"
ON public.nutrition_plan_meals FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.nutrition_plans
    WHERE nutrition_plans.id = nutrition_plan_meals.plan_id
    AND nutrition_plans.user_id = auth.uid()
  )
);

CREATE POLICY "Users can update their own plan meals"
ON public.nutrition_plan_meals FOR UPDATE
USING (
  EXISTS (
    SELECT 1 FROM public.nutrition_plans
    WHERE nutrition_plans.id = nutrition_plan_meals.plan_id
    AND nutrition_plans.user_id = auth.uid()
  )
);

-- Timestamp trigger for updated_at
CREATE TRIGGER update_client_nutrition_profiles_updated_at
BEFORE UPDATE ON public.client_nutrition_profiles
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_nutrition_plans_updated_at
BEFORE UPDATE ON public.nutrition_plans
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Create indexes
CREATE INDEX idx_nutrition_plans_user_id ON public.nutrition_plans(user_id);
CREATE INDEX idx_nutrition_plan_meals_plan_id ON public.nutrition_plan_meals(plan_id);
CREATE INDEX idx_nutrition_plan_meals_day_number ON public.nutrition_plan_meals(plan_id, day_number);
